function power_matrix = get_unflaten_for_heatmap( ...
    method, ...
    power_vec, ...
    method_level, ...
    grouped_data ...
)


    if strcmp(method_level.(method),'variable')

        % Edge case — direct unflatten
        power_matrix = unflatten_matrix( ...
            power_vec, ...
            grouped_data.mask, ...
            grouped_data.map_type ...
        );
    
    elseif strcmp(method_level.(method),'network')

        % Network case — project network values into edge space, then unflatten
        power_matrix = unflatten_network( ...
            power_vec, ...
            grouped_data.edge_groups, ...
            grouped_data.map_type ...
        );
    
    elseif strcmp(method_level.(method),'whole_brain')

        fprintf( ...
            '[SKIP] %s: %d variables — cannot map to edge or network space.\n', ...
            method, ...
            numel(power_vec) ...
        );
        power_matrix = NaN;

    else

        error( ...
            'get_unflaten_for_heatmap:unknownLevel', ...
            ['Unknown method level ''%s'' for method ''%s''. ' ...
'           Expected ''variable'', ''network'', or ''whole_brain''.'], ...
            method_level.(method), ...
            method ...
        );
    
    end


end
