function heatmap_figure_generation( ...
    sample_size_index, ...
    power_by_method, ...
    method_level, ...
    grouped_data, ...
    ALL_METHODS ...
)
    
    % Extract needed variables
    dataset          = grouped_data.dataset;
    map_type         = grouped_data.map_type;
    task             = grouped_data.task;
    test             = grouped_data.test;
    mask             = grouped_data.mask;
    output_group_dir = grouped_data.output_group_dir;
    current_n        = grouped_data.sample_sizes(sample_size_index);

    % Get sample size key
    sample_size_key = sprintf('n%d', current_n);

    for method_idx = 1:length(ALL_METHODS)
        method    = ALL_METHODS{method_idx};
        power_vec = power_by_method.(method)(sample_size_index, :);
        
        power_matrix = get_unflaten_for_heatmap( ...
            method, ...
            power_vec, ...
            method_level, ...
            grouped_data ...
        );

        if isscalar(power_matrix) && isnan(power_matrix)
            continue
        end

        switch map_type
    
            case 'act'
    
                fig = figure('Visible', 'off', 'Color', [0.06 0.07 0.10], ...
                         'Position', [0 0 800 800]);

                ax  = axes('Parent', fig, ...
                           'Color',  [0.10 0.11 0.18], ...
                           'XColor', [0.58 0.64 0.73], ...
                           'YColor', [0.58 0.64 0.73]);
                
                [x, y, z] = ind2sub(size(power_matrix), find(mask));

                values = power_matrix(mask);
                above_thresh = values > 5;

                scatter3( ...
                    ax, ...
                    x(above_thresh), ...
                    y(above_thresh), ...
                    z(above_thresh), ...
                    5, ...
                    values(above_thresh), ...
                    'filled' ...
                );

                colorbar_handle = colorbar(ax);
                set(get(colorbar_handle, 'label'), 'string', 'Power (%)');
                set(get(colorbar_handle, 'label'), 'color', [0 0 0]);
                set(get(colorbar_handle, 'label'), 'FontSize', 14);

                clim(ax, [0 100]);
                custom_map = [ones(256,1), linspace(0.85, 0.0, 256)', linspace(0.85, 0.0, 256)'];
                colormap(ax, custom_map);

                view(ax, 45, 30);
                axis(ax, 'equal');
                axis(ax, 'off');

                dataset_title  = strrep(upper(dataset),  '_', ' ');
                map_type_title = strrep(upper(map_type), '_', ' ');
                task_title     = strrep(task,   '_', ' ');
                test_title     = strrep(test,   '_', ' ');
                method_title   = strrep(method, '_', ' ');

                title( ...
                    ax, ...
                    sprintf('%s | %s | %s | test=%s\n%s  |  n=%d', ...
                    dataset_title, map_type_title, task_title, ...
                    test_title, method_title, current_n), ...
                    'Color', [0 0 0], ...
                    'FontSize', 14 ...
                );
                
                file_name = fullfile( ...
                    output_group_dir, ...
                    sprintf('heatmap_%s_%s.png', ...
                    method, ...
                    sample_size_key) ...
                ); 

                save_figure( ...
                    fig, ...
                    file_name, ...
                    150, ...
                    [0.06 0.07 0.10] ...
                    );

                close(fig);
    
            case 'fc'
    
                fig = figure('Visible', 'off', 'Color', [0.06 0.07 0.10], ...
                     'Position', [0 0 800 700]);

                ax  = axes('Parent', fig, ...
                           'Color',  [0.10 0.11 0.18], ...
                           'XColor', [0.58 0.64 0.73], ...
                           'YColor', [0.58 0.64 0.73]);
    
                imagesc(ax, power_matrix, [0 100]);
                colorbar_handle = colorbar(ax);
                set(get(colorbar_handle, 'label'), 'string', 'Power (%)');
                set(get(colorbar_handle, 'label'), 'color', [0 0 0]);
                set(get(colorbar_handle, 'label'), 'FontSize', 14);
    
                dataset_title = strrep(upper(dataset), '_', ' ');
                map_type_title = strrep(upper(map_type), '_', ' ');
                task_title = strrep(task, '_', ' ');
                test_title = strrep(test, '_', ' ');
                method_title = strrep(method, '_', ' ');
                
                heat_map_title = sprintf('%s | %s | %s | test=%s\n%s  |  n=%d', ...
                    dataset_title, ...
                    map_type_title, ...
                    task_title, ...
                    test_title, ...
                    method_title, ...
                    current_n);

                title( ...
                    ax, ...
                    heat_map_title, ...
                    'Color', [0 0 0], ...
                    'FontSize', 14 ...
                );

                xlabel(ax, 'Node index', 'Color', [0 0 0], 'FontSize', 12);
                ylabel(ax, 'Node index', 'Color', [0 0 0], 'FontSize', 12);
                axis(ax, 'square');
                
                file_name = fullfile( ...
                    output_group_dir, ...
                    sprintf('heatmap_%s_%s.png', method, sample_size_key) ...
                );

                save_figure( ...
                  fig, ...
                  file_name, ...
                  150, ...
                  [0.06 0.07 0.10] ...
                ); 

                close(fig);
    
            otherwise

                error('Heatmap map_type %s not supported.', map_type);
    
        end
    
    end


end