function mean_figure_generation( ...
    quantile, ...
    quantile_power, ...
    grouped_data, ...
    curve_fits, ...
    ALL_METHODS ...
)
    
    % Get necessary group data
    dataset          = grouped_data.dataset;
    map_type         = grouped_data.map_type;
    task             = grouped_data.task;
    test             = grouped_data.test;
    sample_sizes     = grouped_data.sample_sizes;
    output_group_dir = grouped_data.output_group_dir;
    
    % Average power figures
    fig = figure('Visible', 'off', 'Color', [0.06 0.07 0.10], ...
        'Position', [0 0 1100 500]);
    ax  = axes('Parent', fig, ...
        'Color',     [0.10 0.11 0.18], ...
        'XColor',    [0.58 0.64 0.73], ...
        'YColor',    [0.58 0.64 0.73], ...
        'GridColor', [0.16 0.19 0.29], ...
        'GridAlpha', 0.4);
    hold(ax, 'on');
    grid(ax, 'on');
    
    for method_idx = 1:length(ALL_METHODS)
        method          = ALL_METHODS{method_idx};
        mean_power_by_n = quantile_power.(method);
        color           = map_method_name_to_color(method);
        
        % Type of figure
        scatter( ...
            ax, ...
            sample_sizes, ...
            mean_power_by_n, ...
            60, ...
            color, ...
            'filled', ...
            'HandleVisibility', ...
            'off' ...
        );
    
        if ~isempty(curve_fits.(method))
            % Retrieve curve fit
            fitted_curve   = curve_fits.(method);
            
            % Points to calculate curve
            n_interpolated = linspace( ...
                min(sample_sizes), ...
                max(sample_sizes) * 2, ...
                300 ...
            );

            fitted_power = power_curve_fn( ...
                n_interpolated, ...
                fitted_curve.P, ...
                fitted_curve.a, ...
                fitted_curve.b ...
            );

            plot( ...
                ax, ...
                n_interpolated, ...
                fitted_power, ...
                'Color',       color, ...
                'LineWidth',   2, ...
                'DisplayName', map_method_name_to_plot_name(method) ...
            );
    
        else

            plot(ax, nan, nan, 'Color', color, 'LineWidth', 2, ...
                'DisplayName', sprintf('%s  (insufficient data)', method));

        end
    end
    
    dataset_title = strrep(upper(dataset), '_', ' ');
    map_type_title = strrep(upper(map_type), '_', ' ');
    taks_title = strrep(task, '_', ' ');
    test_title = strrep(test, '_', ' ');
    
    plot( ...
        ax, ...
        [min(sample_sizes) max(sample_sizes)*2], ...
        [80 80], ...
        '--', ...
        'Color', [0.96 0.62 0.07], ...
        'LineWidth', 1.2 ...
    );
    
    legend(ax, 'TextColor', [0.89 0.91 0.94], ...
        'Color', [0.10 0.11 0.18], 'EdgeColor', [0.30 0.33 0.45], ...
        'Location', 'eastoutside');

    xlabel(ax, 'Sample size (n)', 'Color', [0 0 0], 'FontSize', 12);
    ylabel(ax, 'Power (%)',       'Color', [0 0 0], 'FontSize', 12);
    ylim(ax, [-2 105]);
    
    quantile_label = sprintf('top %g%%', quantile * 100);   

    title( ...
        ax, ...
        sprintf('%s | %s | %s | test=%s | %s', ...
        dataset_title, map_type_title, taks_title, test_title, quantile_label), ...
        'Color', [0 0 0], ...
        'FontSize', 14, ...
        'FontWeight', 'bold' ...
        );
    

    q_tag = sprintf('q%d', round(quantile * 100));  % q10, q20, ... q100
    save_figure( ...
        fig, ...
        fullfile(output_group_dir, sprintf('power_curve_top_%s.png', q_tag)), ...
        150, ...
        [0.06 0.07 0.10] ...
    );

    close(fig);

end