function save_figure(fig, path, resolution, background_color)

    if exist('exportgraphics', 'builtin') || exist('exportgraphics', 'file')
        exportgraphics( ...
            fig, ...
            path, ...
            'Resolution', resolution, ...
            'BackgroundColor', background_color ...
            );
    else
        print( ...
            fig, ...
            path, ...
            '-dpng', ...
            sprintf('-r%d', resolution) ...
            );
    end

end
