FILE_TO_OUTCOME = {
    "REST_EMOTION":    "EMOTION",
    "REST_GAMBLING":   "GAMBLING",
    "REST_RELATIONAL": "RELATIONAL",
    "REST_SOCIAL":     "SOCIAL",
    "REST_WM":         "WORKING MEMORY",
}