FILE_TO_OUTCOME = {
    # HCP tasks
    "REST_EMOTION":    "Emotion",
    "REST_GAMBLING":   "Gambling",
    "REST_RELATIONAL": "Relational",
    "REST_SOCIAL":     "Social",
    "REST_WM":         "Working Memory",
    # HCP Activation
    "EMOTION":    "Emotion",
    "GAMBLING":   "Gambling",
    "RELATIONAL": "Relational",
    "SOCIAL":     "Social",
    "WM":         "Working Memory",
    # ABCD demographics
    "sex":             "Sex",
    "wisc_v_iq":       "WISC-V IQ",
    "age":             "Age",
    "bmi_z":           "BMI z-score",
    # ABCD CBCL baseline
    "cbcl_internalizing": "CBCL Internalizing",
    "cbcl_externalizing": "CBCL Externalizing",
    "cbcl_aggressive":    "CBCL Aggressive",
    "cbcl_rule_breaking": "CBCL Rule Breaking",
    "cbcl_attention":     "CBCL Attention",
    "cbcl_thought":       "CBCL Thought Problems",
    "cbcl_social":        "CBCL Social Problems",
    "cbcl_somatic":       "CBCL Somatic",
    "cbcl_withdrawn":     "CBCL Withdrawn",
    "cbcl_anx_dep":       "CBCL Anxious/Depressed",
    # ABCD UPPS impulsivity
    "upps_lack_planning":      "UPPS Lack of Planning",
    "upps_lack_perseverance":  "UPPS Lack of Perseverance",
    "upps_sensation_seeking":  "UPPS Sensation Seeking",
    "upps_neg_urgency":        "UPPS Negative Urgency",
    "upps_pos_urgency":        "UPPS Positive Urgency",
    # ABCD substance use
    "substance_use": "Substance Use",
    # ABCD CBCL follow-up 1
    "cbcl_internalizing_fu1": "CBCL Internalizing (FU1)",
    "cbcl_externalizing_fu1": "CBCL Externalizing (FU1)",
    "cbcl_aggressive_fu1":    "CBCL Aggressive (FU1)",
    "cbcl_rule_breaking_fu1": "CBCL Rule Breaking (FU1)",
    "cbcl_attention_fu1":     "CBCL Attention (FU1)",
    "cbcl_thought_fu1":       "CBCL Thought Problems (FU1)",
    "cbcl_social_fu1":        "CBCL Social Problems (FU1)",
    "cbcl_somatic_fu1":       "CBCL Somatic (FU1)",
    "cbcl_withdrawn_fu1":     "CBCL Withdrawn (FU1)",
    "cbcl_anx_dep_fu1":       "CBCL Anxious/Depressed (FU1)",
    # ABCD CBCL change scores
    "cbcl_internalizing_delta": "CBCL Internalizing (Δ)",
    "cbcl_externalizing_delta": "CBCL Externalizing (Δ)",
    "cbcl_aggressive_delta":    "CBCL Aggressive (Δ)",
    "cbcl_rule_breaking_delta": "CBCL Rule Breaking (Δ)",
    "cbcl_attention_delta":     "CBCL Attention (Δ)",
    "cbcl_thought_delta":       "CBCL Thought Problems (Δ)",
    "cbcl_social_delta":        "CBCL Social Problems (Δ)",
    "cbcl_somatic_delta":       "CBCL Somatic (Δ)",
    "cbcl_withdrawn_delta":     "CBCL Withdrawn (Δ)",
    "cbcl_anx_dep_delta":       "CBCL Anxious/Depressed (Δ)",
}